### PR TITLE
feat: switch between split, code, map and legend view with a group button instead of a accordion

### PR DESCRIPTION
**Pull request by OSHistory**
Hello, 

Looking forward to the upcoming code-sprint :). To get a bit into React programming I made a minor (?) change to the UI: Instead of the existing accordion based toggle between map, code and legend display it uses a button group (same as OpenLayers / SLD button). 

I figured that it would be a feature to have both the map and the code displayed at the same time, as it is possible in its current state. So I added a Split view (split is controlled by CSS). 

The visibility is controlled by the `hidden` attribute as the state needs to be preserved (or else the code style-dropdown or the map extent would constantly be reset). 

This PR would take care of: 

https://github.com/geostyler/geostyler-demo/issues/402

Additionaly it fixes a bug which is not yet reported. If the code editor is expanded (initial state), the map can not be expanded. The console displays the OpenLayers error: `No map visible because the map container's width or height are 0.` 

Greetings, 

Niklas

### CODE REVIEW

**Comment by KaiVolland** [comment]
I'll have a look at it and might tweak some css stuff.

**Comment by KaiVolland** [comment]
I create a PR against your branch. You may want to check and merge it https://github.com/OSHistory/geostyler-demo/pull/1. I guess this is good to go afterwards.

**Comment by OSHistory** [comment]
Thanks for the CSS edits. Looking good :smile:

**Comment by OSHistory** [comment]
I used the locale Object to reenable language support. Also added a new member `splitView` and added the translations for the languages i felt comfortable in

**Pull request merged**
