### PR TITLE
Add feedback when loading data

### PR DESCRIPTION
**Pull request by jansule**
This adds visual feedback as soon as any data was loaded.

geostyler-demo-loading-feedback

### CODE REVIEW

**Review by KaiVolland — APPROVED** [review]
Nice. Could you resolve the issue of the neverending spinning circle when uploading a file?

**Comment by jansule** [comment]
> Could you resolve the issue of the neverending spinning circle when uploading a file?

Yes. But this needs to be fixed in the geostyler repo, as the buttons are implemented there

**Pull request merged**
