### PR TITLE
Upgrade GeoStyler to v5

### PR DESCRIPTION
**Pull request by chrismayer**
The upgrade to [GeoStyler v5](https://github.com/geostyler/geostyler/releases/tag/v5.0.0) brings some breaking changes at least the demo application does not start any more.

```
geostyler-demo/node_modules/geostyler/dist/Component/Symbolizer/Field/OpacityField/OpacityField.d.ts
TypeScript error in geostyler-demo/node_modules/geostyler/dist/Component/Symbolizer/Field/OpacityField/OpacityField.d.ts(3,18):
Interface 'OpacityFieldProps' incorrectly extends interface 'Partial<InputNumberProps>'.
  Types of property 'onChange' are incompatible.
    Type '((opacity: number | undefined) => void) | undefined' is not assignable to type '((value: string | number | null | undefined) => void) | undefined'.
      Type '(opacity: number | undefined) => void' is not assignable to type '(value: string | number | null | undefined) => void'.
        Types of parameters 'opacity' and 'value' are incompatible.
          Type 'string | number | null | undefined' is not assignable to type 'number | undefined'.
            Type 'null' is not assignable to type 'number | undefined'.  TS2430
```

### CODE REVIEW

**Comment by KaiVolland** [comment]
Actually i couldn't reproduce your issue above, but i found some others. Maybe you like to check it out again and give it a try.
These PRs in geostyler are realted:
https://github.com/geostyler/geostyler/pull/1356
https://github.com/geostyler/geostyler/pull/1357
https://github.com/geostyler/geostyler/pull/1358

**Comment by KaiVolland** [comment]
Pro tip: Don't write `partially fixes` in previous to a pullerequest link!

**Comment by KaiVolland** [comment]
@chrismayer Do you think you'll find some time to check if this ok for you now?

**Comment by weskamm** [comment]
i can confirm that the current state of this PR works well - at least in dev mode. upgrading geostyler repo to 5.0.1 still works and looks even better!

**Comment by KaiVolland** [comment]
> i can confirm that the current state of this PR works well - at least in dev mode. upgrading geostyler repo to 5.0.1 still works and looks even better!

Thanks for the hint. I'll update this PR to use `5.0.1`.

**Comment by chrismayer** [comment]
I just tested with the latest state. Works like charm. Thanks for picking up the ball and fixing this!

**Pull request merged**
